### ISSUE TITLE
Error deploying FortiGate/Active-Passive-ELB-ILB

### ISSUE THREAD

**Issue by RuiMatosCvT** [40net-cloud/fortinet-azure-solutions#90]
Hi there!

I've tried to deploy this solution on an Azure test Subscription using Azure Cloud Shell and if throws an error while attempting to create NIC4 for both vms.

Deployment failed. Correlation ID: 29dddaf0-66ca-4b9e-aad0-c2f1fb7edcb3. {
  "error": {
    "code": "InvalidRequestFormat",
    "message": "Cannot parse the request.",
    "details": [
      {
        "code": "MissingJsonReferenceId",
        "message": "Value for reference id is missing. Path properties.ipConfigurations[0].properties.publicIPAddress."
      }
    ]
  }
}

Same error occurs while trying to create using the ARM template directly on Azure Portal.

[error.txt](https://github.com/40net-cloud/fortinet-azure-solutions/files/6095364/error.txt)

**Comment by jvhoof** [comment]
Thanks for using our templates and sumitting this issue. We are aware of the error. We are in the process of adding new features and had some issues. This should be fixed with the updates I just commited. I've not tested it completely. If you want to use a template that certainly will deploy use the stable versions on the official Fortinet GitHub here:

https://github.com/fortinet/azure-templates/

Regards,

Joeri

**Comment by RuiMatosCvT** [comment]
Thank you for such a quick answer. I've managed to successfully deploy the template with latest changes.

**Comment by jvhoof** [comment]
Good to hear! Glad it worked.
